DROP TABLE HOTEL;
DROP TABLE HOTEL_TYPE;
DROP TABLE GUEST;
DROP TABLE CONTACT;
DROP TABLE ROOM;
DROP TABLE ROOM_SPECS;
DROP TABLE SPECS;
DROP TABLE ROOM_TYPE;
DROP TABLE RESERVATION;
DROP TABLE RESERVED_ROOM;
DROP TABLE CITY;
DROP TABLE COUNTRY;


alter session set nls_language='ENGLISH';
alter session set nls_date_format='DD-MON-YYYY'; 

CREATE TABLE HOTEL( 
    HOTEL_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    NAME VARCHAR2(30),
    CONTACT_ID NUMBER(4),
    RATE NUMBER(4),
    RATE_COUNT NUMBER(4),
    TYPE_ID NUMBER(4),
    TOTAL_ROOM NUMBER(4),
    CONSTRAINT hotel_pk PRIMARY KEY (HOTEL_ID)
);
CREATE TABLE HOTEL_TYPE(
    HTYPE_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    HTYPE VARCHAR2(30),
    CONSTRAINT htype_pk PRIMARY KEY (HTYPE_ID)
);

CREATE TABLE GUEST(
    GUEST_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    NAME_SURNAME VARCHAR2(30),
    DOB DATE,
    CONTACT_ID NUMBER(4),
    ADDRESS VARCHAR2(50),
    CONSTRAINT guest_pk PRIMARY KEY (GUEST_ID)
);

CREATE TABLE CONTACT(
    CONTACT_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    CONTACT_TYPE CHAR(1),
    TELEPHONE VARCHAR2(50),
    CITY_ID NUMBER(4),
    PBX VARCHAR2(50),
    EMAIL VARCHAR2(50),
    CONSTRAINT contact_pk PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE ROOM_TYPE(
    RTYPE_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    RTYPE VARCHAR2(30),
    CONSTRAINT rtype_pk PRIMARY KEY (RTYPE_ID)
);

CREATE TABLE COUNTRY(
    COUNTRY_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    COUNTRY_NAME VARCHAR2(30),
    CONSTRAINT country_pk PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE ROOM(
    ROOM_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    HOTEL_ID NUMBER(4),
    ROOM_TYPE NUMBER(4),
    ROOM_SIZE VARCHAR2(3),
    SINGLE_BED NUMBER,
    FRENCH_BED NUMBER,
    ROOM_PRICE VARCHAR2(8),
    CONSTRAINT room_pk PRIMARY KEY (ROOM_ID)
);

CREATE TABLE ROOM_SPECS(
    RS_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    ROOM_ID NUMBER(4),
    SPEC_ID NUMBER(4),
    CONSTRAINT rspec_pk PRIMARY KEY (RS_ID)
);

CREATE TABLE SPECS(
    SPEC_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    SPEC VARCHAR2(30),
    CONSTRAINT spec_pk PRIMARY KEY (SPEC_ID)
);

CREATE TABLE CITY(
    CITY_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    CITY_NAME VARCHAR2(30),
    COUNTRY_ID NUMBER(4),
    CONSTRAINT city_pk PRIMARY KEY (CITY_ID)
);

CREATE TABLE RESERVATION(
    RESERVATION_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    CHECK_IN DATE,
    CHECK_OUT DATE,
    HOTEL_ID NUMBER(4),
    GUEST_ID NUMBER(4),
    PEOPLE_COUNT VARCHAR2(2),
    AMOUNT VARCHAR2(8),
    CONSTRAINT reservation_pk PRIMARY KEY (RESERVATION_ID)
);
CREATE TABLE RESERVED_ROOM(
    RESERVED_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    ROOM_ID NUMBER(4),
    RESERVATION_ID NUMBER(4),
    CONSTRAINT reserved_pk PRIMARY KEY (RESERVED_ID)
);

INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('TURKEY');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('UNITED KINGDOM');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('GERMANY');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('FRANCE');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('UNITED STATES OF AMERICA');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('RUSSIA');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('SWEDEN');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('NORWAY');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('SPAIN');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES('ITALY');


INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('ISTANBUL',1);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('ANKARA',1);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('IZMIR',1);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('BREE',2);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('SHIRE',2);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('PARIS',4);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('NEW YORK',5);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('MOSCOW',6);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('STOCKHOLM',7);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('SEVILLA',9);
INSERT INTO CITY(CITY_NAME,COUNTRY_ID) VALUES('BIRMINGHAM',2);

INSERT INTO HOTEL_TYPE (HTYPE) VALUES('RESORT');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('HOLIDAY VILLAGE');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('CAMPING');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('HOSTEL');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('CASINO HOTEL');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('BOUTIQUE HOTEL');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('GARDEN HOTEL');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('MOTEL');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('PENSION');
INSERT INTO HOTEL_TYPE (HTYPE) VALUES('CAPSULE HOTEL');

INSERT INTO SPECS (SPEC) VALUES('AIR-CONDITIONER');
INSERT INTO SPECS (SPEC) VALUES('WIFI');
INSERT INTO SPECS (SPEC) VALUES('MINIBAR');
INSERT INTO SPECS (SPEC) VALUES('SECURE SAFE');
INSERT INTO SPECS (SPEC) VALUES('TV');
INSERT INTO SPECS (SPEC) VALUES('SEA VIEW');
INSERT INTO SPECS (SPEC) VALUES('MOUNTAIN VIEW');
INSERT INTO SPECS (SPEC) VALUES('POOL VIEW');
INSERT INTO SPECS (SPEC) VALUES('AIR VIEW');
INSERT INTO SPECS (SPEC) VALUES('JACUZZI');

INSERT INTO ROOM_TYPE (RTYPE) VALUES('HONEYMOON SUITE');
INSERT INTO ROOM_TYPE (RTYPE) VALUES('KING SUITE');
INSERT INTO ROOM_TYPE (RTYPE) VALUES('QUEEN SUITE');
INSERT INTO ROOM_TYPE (RTYPE) VALUES('KNIGHT SUITE');
INSERT INTO ROOM_TYPE (RTYPE) VALUES('PAWN SUITE');
INSERT INTO ROOM_TYPE (RTYPE) VALUES('FAMILY SUITE');


INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('h','02321112233',1,'12346789','BUDAPEST@BUDAPEST.COM');
INSERT INTO HOTEL(NAME,CONTACT_ID,RATE,RATE_COUNT,TYPE_ID,TOTAL_ROOM) VALUES('GRAND BUDAPEST HOTEL',1,0,1,1,100);

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('h','1321564894',3,'465465456','SWISS@SWISS.COM');
INSERT INTO HOTEL(NAME,CONTACT_ID,RATE,RATE_COUNT,TYPE_ID,TOTAL_ROOM) VALUES('Swissotel',2,0,1,7,200);

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('h','2312312312',3,'234234324','HILTON@HILTON.COM');
INSERT INTO HOTEL(NAME,CONTACT_ID,RATE,RATE_COUNT,TYPE_ID,TOTAL_ROOM) VALUES('HILTON',3,0,1,4,150);

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('h','7987987987',11,'21321414124','SHELBY@SHELBY.COM');
INSERT INTO HOTEL(NAME,CONTACT_ID,RATE,RATE_COUNT,TYPE_ID,TOTAL_ROOM) VALUES('Peaky Blinders',4,0,1,5,1500);

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('h','1111111111',4,'1111111111','PRANCINGPONY@PRANCINGPONY.COM');
INSERT INTO HOTEL(NAME,CONTACT_ID,RATE,RATE_COUNT,TYPE_ID,TOTAL_ROOM) VALUES('Inn of the Prancing Pony',5,0,1,5,5);


INSERT INTO ROOM (HOTEL_ID, ROOM_TYPE, ROOM_SIZE,SINGLE_BED,FRENCH_BED,ROOM_PRICE) VALUES(1,1,'80',0,1,'150');
INSERT INTO ROOM (HOTEL_ID, ROOM_TYPE, ROOM_SIZE,SINGLE_BED,FRENCH_BED,ROOM_PRICE) VALUES(1,6,'50',2,1,'100');

INSERT INTO ROOM (HOTEL_ID, ROOM_TYPE, ROOM_SIZE,SINGLE_BED,FRENCH_BED,ROOM_PRICE) VALUES(2,2,'100',0,1,'250');
INSERT INTO ROOM (HOTEL_ID, ROOM_TYPE, ROOM_SIZE,SINGLE_BED,FRENCH_BED,ROOM_PRICE) VALUES(2,5,'20',1,0,'40');

INSERT INTO ROOM (HOTEL_ID, ROOM_TYPE, ROOM_SIZE,SINGLE_BED,FRENCH_BED,ROOM_PRICE) VALUES(3,3,'80',1,1,'150');
INSERT INTO ROOM (HOTEL_ID, ROOM_TYPE, ROOM_SIZE,SINGLE_BED,FRENCH_BED,ROOM_PRICE) VALUES(3,4,'80',1,1,'100');

INSERT INTO ROOM_SPECS(ROOM_ID,SPEC_ID) VALUES(1,1);
INSERT INTO ROOM_SPECS(ROOM_ID,SPEC_ID) VALUES(1,2);
INSERT INTO ROOM_SPECS(ROOM_ID,SPEC_ID) VALUES(2,1);
INSERT INTO ROOM_SPECS(ROOM_ID,SPEC_ID) VALUES(2,5);
INSERT INTO ROOM_SPECS(ROOM_ID,SPEC_ID) VALUES(3,4);
INSERT INTO ROOM_SPECS(ROOM_ID,SPEC_ID) VALUES(4,6);

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('g','1111111111',5,'1111111111','ringbearer@bagend.com');
INSERT INTO GUEST(NAME_SURNAME, DOB, CONTACT_ID, ADDRESS) VALUES('FRODO BAGGINS', TO_DATE('22-SEP-2968', 'DD-MON-YYYY'),6,'SHIRE BAGEND');

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('g','1111111111',3,'1111111111','oguzgul@std.iyte.edu.tr');
INSERT INTO GUEST(NAME_SURNAME, DOB, CONTACT_ID, ADDRESS) VALUES('OGUZ GUL', TO_DATE('22-AUG-1995', 'DD-MON-YYYY'),7,'IYTE');

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('g','1111111111',3,'1111111111','bugrahandonmez@std.iyte.edu.tr');
INSERT INTO GUEST(NAME_SURNAME, DOB, CONTACT_ID, ADDRESS) VALUES('BUGRAHAN DONMEZ', TO_DATE('13-DEC-1995', 'DD-MON-YYYY'),8,'IYTE');

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('g','1111111111',2,'1111111111','leventaozen@std.iyte.edu.tr');
INSERT INTO GUEST(NAME_SURNAME, DOB, CONTACT_ID, ADDRESS) VALUES('LEVENT ANIL OZEN', TO_DATE('01-JAN-1995', 'DD-MON-YYYY'),9,'IYTE');

INSERT INTO CONTACT (CONTACT_TYPE,TELEPHONE,CITY_ID,PBX,EMAIL) VALUES('g','1111111111',3,'1111111111','tugbaaydogmus@std.iyte.edu.tr');
INSERT INTO GUEST(NAME_SURNAME, DOB, CONTACT_ID, ADDRESS) VALUES('TUGBANUR AYDOGMUS', TO_DATE('01-JAN-1995', 'DD-MON-YYYY'),10,'IYTE');




